### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
adapter_name_or_path: saves/llama3-8b/lora/sft
cache_dir: /data2/.shared_models
template: llama3
trust_remote_code: true

### export
export_dir: output/llama3_lora_sft
export_size: 5
export_device: cpu
export_legacy_format: false